#!/bin/bash

./prlctlall.py --build exec 'bash -c "cd srcML; svn update"'

./prlctlall.py --fedora --build exec 'bash -c "cd srcML/trunk/src; make clean; make"'
./prlctlall.py --fedora --build exec 'bash -c "cd srcML/trunk/srcdiff/trunk/dist; make clean; make"'
./prlctlall.py --fedora --build exec 'bash -c "chown -R srcml:srcml srcML"'
scp fedora15build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora15
scp fedora16build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora16


./prlctlall.py --fedora --build exec 'bash -c "cd srcML/trunk/src; make clean; make mingw32"'
./prlctlall.py --fedora --build exec 'bash -c "cd srcML/trunk/srcdiff/trunk/dist; make clean; make windows"'
#rm -rf ~/Dropbox/srcML/Unix/Fedora16/srcML*
./prlctlall.py --fedora --build exec 'bash -c "chown -R srcml:srcml srcML"'
scp fedora15build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.zip ~/Dropbox/srcML/Windows
cd ~/Dropbox/srcML/Windows; unzip srcDiff-Win.zip
cd

./prlctlall.py --ubuntu --build exec 'bash -c "cd srcML/trunk/src; make clean; make"'
./prlctlall.py --ubuntu --build exec 'bash -c "cd srcML/trunk/srcdiff/trunk/dist; make clean; make"'

#rm -rf ~/Dropbox/srcML/Unix/Ubuntu10.04/srcML*
#rm -rf ~/Dropbox/srcML/Unix/Ubuntu11.04/srcML*
./prlctlall.py --ubuntu --build exec 'bash -c "chown -R srcml:srcml srcML"'
scp ubuntu10build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu10.04
scp ubuntu11build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu11.04
scp ubuntu12build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu12.04-64

cd srcML; svn update
cd

cd srcML/trunk/src; make clean; make;
cd
cd srcML/trunk/srcdiff/trunk/dist; make clean; make;
cp *.tar.gz ~/Dropbox/srcML/Unix/OSX
cd