#!/bin/bash

./prlctlall.py --build exec 'bash -c "cd srcML; svn update"'

./prlctlall.py --build exec 'bash -c "cd srcML/trunk/src; make clean; make"'
./prlctlall.py --build exec 'bash -c "cd srcML/trunk/srcdiff/trunk/dist; make clean; make"'
./prlctlall.py --build exec 'bash -c "chown -R srcml:srcml srcML"'
scp fedora15build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora15
scp fedora16build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora16
scp fedora17build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora17

scp fedora15build64:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora15-64
scp fedora16build64:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora16-64
scp fedora17build64:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Fedora17-64

scp ubuntu10build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu10.04
scp ubuntu11build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu11.04
scp ubuntu12build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu12.04

scp ubuntu10build64:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu10.04-64
scp ubuntu11build64:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu11.04-64
scp ubuntu12build:64/srcML/trunk/srcdiff/trunk/dist/srcDiff*.tar.gz ~/Dropbox/srcML/Unix/Ubuntu12.04-64

./prlctlall.py --fedora --build -15 exec 'bash -c "cd srcML/trunk/src; make clean; make mingw32"'
./prlctlall.py --fedora --build -15 exec 'bash -c "cd srcML/trunk/srcdiff/trunk/dist; make clean; make windows"'

./prlctlall.py --fedora --build --15 exec 'bash -c "chown -R srcml:srcml srcML"'
scp fedora15build:/srcML/trunk/srcdiff/trunk/dist/srcDiff*.zip ~/Dropbox/srcML/Windows
cd ~/Dropbox/srcML/Windows; unzip srcDiff-Win.zip
cd

cd srcML; svn update
cd

cd srcML/trunk/src; make clean; make;
cd
cd srcML/trunk/srcdiff/trunk/dist; make clean; make;
cp *.tar.gz ~/Dropbox/srcML/Unix/OSX
cd