#!/bin/bash

../bin/colordiffc <(../bin/srcdiff --literal --operator --modifier $1 $2) <(diff --old-group-format="d%df-%dl\n" --new-group-format="i%dF-%dL\n" --line-format="" $1 $2 | tr '\\n' '\n' | sed '/^$/d')

