#!/bin/bash

os=$(uname)

MKTEMP="/opt/local/bin/gmktemp"

if [[ $os != "Darwin" ]] 
then

    MKTEMP="/bin/mktemp"

fi

filename=$(${MKTEMP} --suffix=.html)

../test/srcdiffviz $1 $2 > $filename

if [[ $os == "Darwin" ]] 
then
    open -a Safari.app $filename
fi