#!/bin/bash

run="yes"

if [[ ! -f $1 ]]
then

    echo "'$1' Does not exist."
    run="no"

fi

if [[ ! -f $2 ]]
then

    echo "'$2' Does not exist."
    run="no"

fi

if [[ $run == "no" ]]
then

    exit

fi


# check srcdiff for a file pair both ways

src2srcml --literal --operator --modifier $1 -o $1.xml

src2srcml --literal --operator --modifier $2 -o $2.xml

../bin/srcdiff --literal --operator --modifier $1 $2 -o temp;

srcml2src --revision 1 temp -o srcmlold;
srcml2src --revision 2 temp -o srcmlnew;
diff srcmlold $1;
diff srcmlnew $2

srcml2src --xml --revision 1 temp -o srcmlold;
srcml2src --xml --revision 2 temp -o srcmlnew;
diff srcmlold $1.xml;
diff srcmlnew $2.xml

../bin/srcdiff --literal --operator --modifier $2 $1 -o temp;

srcml2src  --revision 1 temp -o srcmlold;
srcml2src --revision 2 temp -o srcmlnew;
diff srcmlold $2;
diff srcmlnew $1

srcml2src --xml --revision 1 temp -o srcmlold;
srcml2src --xml --revision 2 temp -o srcmlnew;
diff srcmlold $2.xml;
diff srcmlnew $1.xml

rm -f temp old new $1.xml $2.xml
