version: 2
jobs:
   build:
     docker:
       - image: ubuntu
     steps:
       - checkout
       - run: echo "hello world"
       - run: mkdir build
       - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release .
       - run: cd test/ && ./test_suite.py