version: 2
jobs:
   build:
     docker:
       - image: srcml/srcdiff_testing
     steps:
       - checkout
       - run: git submodule update --init --recursive
       - run: mkdir build
       - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
       - run: cd build && make
       - run: cd test && ./test_suite.py
       