version: 2
jobs:
   build:
     docker:
       - image: srcml/ubuntu_x86_64_base
     steps:
       - checkout
       # - run: git submodule update --init --recursive
       # - run: mkdir build
       # - run: cd build && git clone --recursive git@github.com:srcML/srcML.git
       # - run: cd build && mkdir srcml_build
       # - run: cd build/srcml_build && cmake ../srcML
       # - run: cd build/srcml_build && sudo make install
       # - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
       # - run: cd build && make
       # - run: cd test && ./test_suite.py