#!/bin/sh
echo "---" $1
if [[ $# -eq 7 ]]; then
    echo "+++" $1
else
    echo "+++" $8
fi

if [[ $2 = "/dev/null" ]]; then
temp_file = srcdiff_temp$(bash -c "echo $5 | grep -o '\.[^.]*$'")
elif [[ $5 = "/dev/null" ]]; then
temp_file = srcdiff_temp$(bash -c "echo $2 | grep -o '\.[^.]*$'")
fi

echo $temp_file

if [[ $2 = "/dev/null" ]]; then

    touch $temp_file
    srcdiff --unified --unified-context=3 $temp_file "$5"
    rm -f $temp_file

elif [[ $5 = "/dev/null" ]]; then

    touch $temp_file   
    srcdiff --unified --unified-context=3 "$2" $temp_file
    rm -f $temp_file

else
    srcdiff --unified --unified-context=3 "$2" "$5"
fi
