---
name: Build for Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest

      - name: Get vcpkg
        uses: lukka/run-vcpkg@v11 
        with:
          vcpkgDirectory: '${{ github.workspace }}/utilities/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows-clang'

env:
  VCPKG_ROOT: '${{ github.workspace }}/utilities/vcpkg'
