---
    name: Build for Ubuntu
    
    on:
      push:
        branches: 
         - 'develop'
      workflow_dispatch:
    
    jobs:
      build_and_test:
        runs-on: ubuntu-latest
        steps:
    
steps:


          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              submodules: true

          - name: Checkout srcML
            uses: actions/checkout@develop
            with:
            name: srcML/srcML    

          - name: Get Latest CMake and Ninja
            uses: lukka/get-cmake@latest
            with:
              cmakeVersion: 3.29.3

          # - name: Get vcpkg
          #   uses: lukka/run-vcpkg@v11 
          #   with:
          #     # this path is arbitrary:
          #     vcpkgDirectory: '${{ github.workspace }}/_tools/vcpkg'
    
          # - name: Get dependencies and configure the build with CMake
          #   uses: lukka/run-cmake@v10
          #   with:
          #     configurePreset: 'gcc-vcpkg'
          #     configurePresetAdditionalArgs: "['-DBUILD_TRANSLATOR_TESTS=ON']"
          
          - name: Run srcML Workflow for Ubuntu 
            run:  | 
              pushd srcML
              cmake --workflow --preset ci-ubuntu
              popd
              ninja install

          - name: Run CI Workflow for Ubuntu
            run: cmake --workflow --preset ci-debian
