---
    name: Build for Ubuntu
    
    on:
      push:
        branches: 
         - 'develop'
      workflow_dispatch:
    
    jobs:
      build_and_test:
        runs-on: ubuntu-latest
        steps:

          - name: Get Latest CMake and Ninja
            uses: lukka/get-cmake@latest
            with:
              cmakeVersion: 3.29.3

          - name: Checkout srcML
            uses: actions/checkout@master
            with:
              repository: srcML/srcML
              ref: develop

          - name: Setup Ubuntu
            shell: bash
            run: |
              sudo apt update
              sudo apt install build-essential ninja-build antlr libarchive-dev libxml2-dev libxslt1-dev \
                               libcurl4-openssl-dev openjdk-21-jre file libboost-dev
          
          - name: Run srcML Workflow for Ubuntu 
            run: |
              cmake --preset ci-ubuntu
              sudo cmake --build ../srcDiff-build -- install

          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
              submodules: true

          - name: Run CI Workflow for Ubuntu
            run: sudo cmake --workflow --preset ci-debian

          # - name: Get vcpkg
          #   uses: lukka/run-vcpkg@v11 
          #   with:
          #     # this path is arbitrary:
          #     vcpkgDirectory: '${{ github.workspace }}/_tools/vcpkg'
    
          # - name: Get dependencies and configure the build with CMake
          #   uses: lukka/run-cmake@v10
          #   with:
          #     configurePreset: 'gcc-vcpkg'
          #     configurePresetAdditionalArgs: "['-DBUILD_TRANSLATOR_TESTS=ON']"
