---
name: Build for Windows

on:
  push:
    branches: 
     - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Get vcpkg
        uses: lukka/run-vcpkg@v11 
        with:
          # this path is arbitrary:
          vcpkgDirectory: '${{ github.workspace }}/_tools/vcpkg'

      - name: Get dependencies and configure the build with CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows'
      
      - name: Build project
        run: cmake --build .
      
      - name: Check if built executable exists and is sane
        shell: pwsh
        run: |
          cd bin
          
          # this is just for logging purposes:
          dir

          # checking that srcdiff actually runs is especially important on
          # windows, since everything can succesfully build but still fail to
          # dynamically link up at runtime
          
          # get version info output:
          $version_info = ./srcdiff -V

          Write-Output "Version info:"
          Write-Output $version_info

          # make sure the string "srcdiff" is somewhere in the version output
          # this is case insensitive
          if (($version_info -match "srcdiff").Length -eq 0){
            exit 1
          }

          Write-Output "Build succeeded!"
